apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-webapp
spec:
  selector:
    matchLabels:
      app: qa-webapp
  template:
    metadata:
      labels:
        app: qa-webapp
    spec:
      containers:
      - name: qa-webapp
        image: "tranphuquy103/web-app-qa-training:1.0.0"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: qa-webapp
spec:
  type: NodePort
  selector:
    app: qa-webapp
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 32767 # http://<node-ip>:32767 to access. <node-ip> is the ip of the container that runs the pod. You can get the ip by inspecting the container with docker inspect <container-id>
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qa-webapp
  labels:
    name: qa-webapp
spec:
  rules:
  - host: qa-webapp.doracoder.dora
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: qa-webapp
            port:
              number: 3000
