version: '3.3'

services:
#   db:
#     profiles:
#       - default
#     image: mysql:5.7
#     volumes:
#       - db_data:/var/lib/mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: somewordpress
#       MYSQL_DATABASE: wordpress
#       MYSQL_USER: wordpress
#       MYSQL_PASSWORD: wordpress
#     networks:
#       - enclave

#   wordpress:
#     profiles:
#       - default
#     depends_on:
#       - db
#     image: wordpress:5.6.0-php8.0
#     ports:
#       - "8000:80"
#     restart: always
#     environment:
#       WORDPRESS_DB_HOST: db:3306
#       WORDPRESS_DB_USER: wordpress
#       WORDPRESS_DB_PASSWORD: wordpress
#       WORDPRESS_DB_NAME: wordpress
# #      WORDPRESS_CONFIG_EXTRA: |
# #        /* Multisite */
# #        define( 'WP_ALLOW_MULTISITE', true );
# #        define('MULTISITE', true);
# #        define('SUBDOMAIN_INSTALL', false);
# #        define('DOMAIN_CURRENT_SITE', 'localhost');
# #        define('PATH_CURRENT_SITE', '/');
# #        define('SITE_ID_CURRENT_SITE', 1);
# #        define('BLOG_ID_CURRENT_SITE', 1);
#     networks:
#       - enclave
  web-app:
    profiles:
      - default
    image: express-app:latest
    build:
      context: ../postman-api-testing
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - enclave

  selenium:
    profiles:
      - test
    image: selenium-mvn-docker:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD/test-output:/opt/enclave/test-output
    networks:
      - enclave
volumes:
  db_data: { }

networks:
  enclave:
    driver: bridge