name: GitHub Actions CI Selenium Docker Example
# on: [push]
permissions: 
  checks: write
  pull-requests: write
on:
  push:
    branches:
    - master
    - dev/add-ci-script
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: selenium-maven-docker
    steps:
    - uses: actions/checkout@v2
    - name: Build selenium-maven-docker
      run: |
        # cd selenium-maven-docker
        # Check if docker-compose is installed
        if ! [ -x "$(command -v docker-compose)" ]; then
          echo 'Error: docker-compose is not installed.' >&2
          exit 1
        fi
        # Build web-app image
        docker-compose -f docker-compose.yml build web-app
        # Build selenium image
        docker-compose -f docker-compose.yml build selenium
    - name: Start web-app
      run: |
        # cd selenium-maven-docker
        docker-compose --profile default -f docker-compose.yml up -d
    - name: Start selenium
      run: |
        # cd selenium-maven-docker
        docker-compose --profile test -f docker-compose.yml up
        echo 'The test-output directory is mounted to the host machine'
        echo 'test-output directory contents:'
        ls -l test-output
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-output
        path: selenium-maven-docker/test-output
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          selenium-maven-docker/test-output/surefire-reports/junitreports/*.xml
