name: Manual trigger the pipeline

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Who to greet'
        required: true
        default: 'World'
      environment:
        description: 'Environment to test'
        required: true
        default: 'dev'
        type: choice
        options:
          - 'dev'
          - 'qa'
          - 'prod'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "Run tests on ${{ github.event.inputs.environment }}!"
