name: Deploy and Test Serverless Application - Todo App
on:
  push:
    paths:
    - 'serverless/**'
    - '.github/workflows/**'

jobs:
  build_publish_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: serverless/todo-api
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # - name: Track changes
    #   run: |
    #       echo "The following files have been changed:"
    #       git diff --name-only HEAD^ HEAD serverless/
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: |
        npm install -g serverless
        npm install
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        serverless config credentials --provider aws --key "$AWS_ACCESS_KEY_ID" --secret "$AWS_SECRET_ACCESS_KEY"
        serverless deploy --stage production --region us-east-1 --verbose
