name: Deploy and Test Serverless Application - Todo App
on:
  push:
    paths:
    - 'serverless/**'
    - '.github/workflows/**'

jobs:
  build_publish_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: serverless/todo-api
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: |
        npm install -g serverless
        npm install -g newman newman-reporter-htmlextra
        npm install
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      run: |
        serverless config credentials --provider aws --key "$AWS_ACCESS_KEY_ID" --secret "$AWS_SECRET_ACCESS_KEY"
        serverless deploy --stage production --region us-east-1 --verbose

        API_GATEWAY_URL=$(serverless info --stage production --region us-east-1 --verbose | awk '/HttpApiUrl/ {print $2}')
        echo "API_GATEWAY_URL=$API_GATEWAY_URL" >> $GITHUB_ENV
    - name: Run tests with Newman
      run: |
        set -x
        newman run collection.json --env-var API_GATEWAY_URL=${{ env.API_GATEWAY_URL }} --reporters cli,htmlextra --reporter-htmlextra-export newman-report.html || EXIT_CODE=$?
        echo "EXIT_CODE=$EXIT_CODE"
    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: newman-report
        path: newman-report.html
